fruits=("apple","banana","mango")
print(fruits)
print(fruits[2])
print(fruits[1])
print(fruits[1:3])
print(fruits[0:])
print("apple" in fruits)
print("cherry" in fruits)
numbers=(1,2,4,5,6,5,4,5)
print(numbers.count(5))